// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKNrMLWjprZWac-C-cJzJcnuqW2zzutlw',
    appId: '1:835474148480:web:2254db0ca3d775e4d16a65',
    messagingSenderId: '835474148480',
    projectId: 'trivago-9a945',
    authDomain: 'trivago-9a945.firebaseapp.com',
    storageBucket: 'trivago-9a945.appspot.com',
    measurementId: 'G-TVD7N0R8TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTP7zopmNzG-jhl91tVq8eI5pNbO2Q5UA',
    appId: '1:835474148480:android:03293b85905dfd50d16a65',
    messagingSenderId: '835474148480',
    projectId: 'trivago-9a945',
    storageBucket: 'trivago-9a945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4S7P-UWh5HSFxfiYbX6gqMLhbXATcHAY',
    appId: '1:835474148480:ios:b227c7fa31abd13dd16a65',
    messagingSenderId: '835474148480',
    projectId: 'trivago-9a945',
    storageBucket: 'trivago-9a945.appspot.com',
    iosBundleId: 'com.example.trivago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4S7P-UWh5HSFxfiYbX6gqMLhbXATcHAY',
    appId: '1:835474148480:ios:692f3d27857dfd3ad16a65',
    messagingSenderId: '835474148480',
    projectId: 'trivago-9a945',
    storageBucket: 'trivago-9a945.appspot.com',
    iosBundleId: 'com.example.trivago.RunnerTests',
  );
}
